apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vm1tojw7g-go
  janus-idp.io/tekton: vm1tojw7g-go
  backstage.io/kubernetes-id: vm1tojw7g-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vm1tojw7g-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
